trigger:
  batch: true
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - README.md
      - doc/**/*

pr:
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - README.md
      - doc/**/*

variables:
  v.prefix: '0.0'
  v.rev: $[counter(variables['v.rev'], 0)]
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Core
    displayName: 'Core Build'
    pool:
      vmImage: $(vmImage)

    steps:

    - task: DotNetCoreCLI@2
      displayName: 'build all'
      inputs:
        command: 'build'
        projects: 'src/Snappy.sln'
        arguments: '-c release /p:Version=$(v.prefix).$(v.rev)'

    - task: DotNetCoreCLI@2
      displayName: 'run tests'
      inputs:
        command: test
        projects: ./src/Snappy.sln
        arguments: '-c release /p:Version=$(v.prefix).$(v.rev)'

    - task: CopyFiles@2
      displayName: 'copy generated nugets'
      inputs:
        SourceFolder: src
        Contents: '**/*.nupkg'
        TargetFolder: ' $(build.artifactstagingdirectory)'
        CleanTargetFolder: true
        OverWrite: true
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      displayName: 'archive nugets'
      inputs:
        ArtifactName: nuget